# Generated by Django 3.2.9 on 2021-11-15 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20211115_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 11, 15, 17, 26, 58, 745558, tzinfo=utc))),
                ('description', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.mediationsessions')),
            ],
        ),
        migrations.CreateModel(
            name='ResolutionPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 11, 15, 17, 26, 58, 745217, tzinfo=utc))),
                ('description', models.CharField(max_length=255)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portofolio', to='core.mediationportafolio')),
            ],
        ),
    ]
