# Generated by Django 3.2.6 on 2021-11-15 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Resolution', '0004_auto_20211115_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionportfolio',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 11, 38, 67051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resolutionsession',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 11, 38, 67494, tzinfo=utc)),
        ),
    ]
