# Generated by Django 3.2.9 on 2021-11-15 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Resolution', '0010_auto_20211115_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionportfolio',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 21, 38, 44, 461803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resolutionsession',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 21, 38, 44, 462124, tzinfo=utc)),
        ),
    ]
