# Generated by Django 3.2.9 on 2021-11-15 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_applicant', to=settings.AUTH_USER_MODEL)),
                ('client_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_defendant', to=settings.AUTH_USER_MODEL)),
                ('lawyer_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_applicant', to=settings.AUTH_USER_MODEL)),
                ('lawyer_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_defendant', to=settings.AUTH_USER_MODEL)),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediationPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime(2021, 11, 15, 17, 26, 50, 1660, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2021, 11, 15, 17, 26, 50, 1684, tzinfo=utc))),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.case')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediationSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediatonPortafolio', to='core.mediationportafolio')),
            ],
        ),
        migrations.AddField(
            model_name='mediationportafolio',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
    ]
