# Generated by Django 2.2 on 2021-11-08 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resolution', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_applicant', to=settings.AUTH_USER_MODEL)),
                ('client_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_defendant', to=settings.AUTH_USER_MODEL)),
                ('lawyer_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_applicant', to=settings.AUTH_USER_MODEL)),
                ('lawyer_defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_defendant', to=settings.AUTH_USER_MODEL)),
                ('meditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediationPortafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Case')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resolution.Resolution')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MediationSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediatonPortafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MediationPortafolio')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resolution.Resolution')),
            ],
        ),
        migrations.AddField(
            model_name='mediationportafolio',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.State'),
        ),
    ]
