# Generated by Django 2.2 on 2021-11-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='meditor',
            new_name='mediator',
        ),
    ]
