# Generated by Django 3.2.6 on 2021-11-15 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211115_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediationportafolio',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 2, 9, 618147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mediationportafolio',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 2, 9, 618124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mediationsessions',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='core.mediationportafolio'),
        ),
    ]
