# Generated by Django 3.2.6 on 2021-11-15 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211115_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediationportafolio',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 4, 7, 320326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mediationportafolio',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 15, 19, 4, 7, 320302, tzinfo=utc)),
        ),
    ]
